name: async-ipfs-api-ci

on:
  pull_request:
    paths:
      - "api/implementations/async-ipfs-api/**"

jobs:
  ci:
    name: async-ipfs-api-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
        working-directory: ./api/implementations/async-ipfs-api

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./api/implementations/async-ipfs-api

      - name: Build
        run: yarn build
        working-directory: ./api/implementations/async-ipfs-api

      # for now, need to build http-plugin-formdata before testing wrapper
      - name: Install http plugin dependencies and build plugin
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline && yarn build
        working-directory: ./http-client/http-plugin-formdata

      # need to build ipfs-http-client before testing wrapper
      - name: build ipfs http client wrapper
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline && yarn build
        working-directory: ./http-client/ipfs-http-client

      - name: Test
        run: yarn test
        working-directory: ./api/implementations/async-ipfs-api