name: ipfs-cat-client-ci

on:
  pull_request:
    paths:
      - "http-client/ipfs-cat-client/**"

jobs:
  ci:
    name: ipfs-cat-client-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
        working-directory: ./http-client/ipfs-cat-client

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./http-client/ipfs-cat-client

      - name: Build
        run: yarn build
        working-directory: ./http-client/ipfs-cat-client

      # for now, need to build http-plugin-timeout before testing wrapper
      - name: Install plugin dependencies and build plugin
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline && yarn build
        working-directory: ./http-plugin-timeout

      - name: Test
        run: yarn test
        working-directory: ./http-client/ipfs-cat-client